project:
  type: website
  output-dir: docs

website:
  title: "Understanding the Increase in Drug Overdose and Alcohol Driving Deaths"


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



